[package]
name = "signature-updater-ms"
version = "0.1.0"
edition = "2021"

[dependencies]
chromiumoxide = "0.7.0"
chrono = "0.4.38"
dotenv = "0.15.0"
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
tokio-cron-scheduler = "0.11.0"
